spring:
  data:
    mongodb:
      uri: mongodb+srv://jarias1028:RtpwHSi9eXdwL4Du@cluster0.2txmapl.mongodb.net/university_db?retryWrites=true&w=majority&appName=Cluster-0
      database: university_db

application:
  name: campus-management

server:
  port: 8080